### ISSUE TITLE
async_tcp.lua: premature close of socket

### ISSUE THREAD

**Issue by joagre** [dmccuskey/DMC-Corona-Library#32]
Hi,
I open an async socket and sends a HTTP request as soon the socket
has entered a CONNECTED state.

The problem: The socket closes abruptly as soon as I sends the HTTP
request though. The strange thing is that I can see (using a network
sniffer) that the HTTP response actually arrives to my machine. If I call
sock:reconnect() as soon as the socket closes I can actually read the
data I see with the network sniffer. AFAICS I should be able to read the
data in the socket buffer even though the socket has been closed?

Your example slightly simplified:
# 

```
local Sockets = require "lib.dmc_corona.dmc_sockets"
local onConnect, dataCallback, newlineCallback

local host = "www.dn.se"
local port = 80
local sock

local function sendRequest()
  local bytes, err
  local req_t, req

  local req_t = {
    "GET / HTTP/1.1\r\n",
    "Host: " .. host .. "\r\n",
    --"User-Agent: DMC Sockets " .. Sockets.__version .. "\r\n",
    "Connection: close" .. "\r\n",
    "\r\n"
  }
  req = table.concat( req_t, "" )
  bytes, err = sock:send( req )
end

newlineCallback = function( event )
  print("== Newline Handler ==")
  event = event or {}

  if not event.data then
    print( event.emsg )
  else
    print("Received Data:\n")
    for i,v in ipairs( event.data ) do
      print(i,v)
    end
    print("\n")

  end
end

onConnect = function(event)
  if event.status == sock.CONNECTED then
    print("=== Connection Established ===")
    sendRequest()
    print("Reading Data\n\n")
    sock:receiveUntilNewline( newlineCallback )
  elseif event.status == sock.CLOSED then
    print("=== Connection Closed ===\n\n")
  else
    print("=== Connection Error ===")
    print( event.emsg )
  end
end

print("Starting Connection")
sock = Sockets:create( Sockets.ATCP )
sock:connect( host, port, { onConnect=onConnect } )
```
# 

The result I see in the console:
# 

```
maj 21 08:13:26.135 Starting Connection
maj 21 08:13:26.171 === Connection Established ===
maj 21 08:13:26.171 Reading Data
maj 21 08:13:26.490 === Connection Closed ===
```
# 

The result I see with a network sniffer:
# 

```
192.168.001.008.63023-095.101.045.192.00080: GET / HTTP/1.1
Host: www.dn.se
Connection: close

095.101.045.192.00080-192.168.001.008.63023: HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
X-Frame-Options: SAMEORIGIN
Content-Length: 333001
Cache-Control: private, max-age=43
Date: Sat, 21 May 2016 18:13:20 GMT
Connection: close
Set-Cookie: weight=34; expires=Fri, 19-Aug-2016 18:13:20 GMT; path=/; domain=.dn.se
Expires: Tue, 01 January 2013 01:00:00 GMT

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html id="ctl00_HtmlElement" xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://opengraphprotocol.org/schema/" xmlns:fb="http://www.facebook.com/2008/fbml">
<head id="ctl00_masterPageHeader"><meta name="ARTICLEFIRSTPUBLISHDATE" property="ARTICLEFIRSTPUBLISHDATE" content="" /><meta name="ARTICLEAUTHORS" property="ARTICLEAUTHORS" content="" /><meta name="CSPAGEURL" property="CSPAGEURL" content="dn.se" /><meta name="CSSEARCH" property="CSSEARCH" content="" /><meta name="CSPAGETYPE" property="CSPAGETYPE" content="Section+with+three+columns" /><meta name="CSPAGENAME" property="CSPAGENAME" content="home.page" /><meta name="CSLEVEL2" property="CSLEVEL2" content="&amp;level-2=none" /><meta name="CSLEVEL1" property="CSLEVEL1" content="&amp;level-1=home" /><meta name="ADSPAGETYPE" property="ADSPAGETYPE" content="Section with three columns" /><meta name="ADSLAYOUT" property="ADSLAYOUT" content="Ettan" /><meta
...
```
# 

I'm most probably dazed and confused. Can you help?

Cheers
/Jocke

**Comment by dmccuskey** [comment]
hello,

i briefly looked through the socket lib and your code. some thoughts:
1. from what you describe, it seems as though the network aspects of your request are working. i would expect the connection to close right after the server has finished processing the request (as part of the HTTP protocol).
   
   this follows what you are seeing in your network packet sniffer. so i seems your issue is more about getting the data.
2. being an async lib, i would guess that this part of your code isn't correct since there's likely not anything to read right after the request has been made
   
   ```
     sendRequest()
     print("Reading Data\n\n")
     sock:receiveUntilNewline( newlineCallback )     <<<< too soon, need to wait
   ```
   
   you need to wait for the notification that there is data available before reading.
3. i looked through the async lib. ATCP has a callback parameter in `sock:connect()` called `onData` (see 182). this function reference will be called when there is data to read.

```
sock:connect( host, port, {
  onConnect=onConnect,
  onData= onDataFunc,
} )
```

the event will contain the following items (see 468):

```
        {
            type = self.READ,
            status = self._status,
            bytes = buff_len
        }
```

in this function, put your read function.

```
function onDataFunc( evt ) {
    sock:receiveUntilNewline( newlineCallback )
}
```

you might want to change how you read the data, too – if the data comes back in one chunk, `receiveUntilNewline()` will only read to the first newline char. that will only read part of your HTML response. though you should be able to do more reads on the socket as you wish, even if the connection is closed.

however, you could do this to get all of the data received:

```
function onDataFunc( evt ) {
    sock:receive( '*a', dataCallback )
}
```

or this to separate out the parts of the reponse: 

```
function onDataFunc( evt ) {
    sock:receiveUntilNewline( newlineCallback )  <<< get reponse headers
    sock:receive( '*a', dataCallback )  <<< read HTML body
}
```

HTH,
dmc

ps, none of the above code is tested :)

**Comment by joagre** [comment]
Thanks for the response!

In other words, sock:receiveUntilNewline() and sock:receive() should only be called by the onDataFunc callback provided to the connect method. They should not be called outside of a onDataFunc context.

That was a surprise but I get it.

Thanks
/Joakim

**Comment by dmccuskey** [comment]
cool ! glad it's working. good luck with your project.

dmc
